package com.needhamsoftware.securesrc.ui;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class EncryptionUpdatePanel extends JPanel {

  private JTextField cipherSpec;
  private JPanel layoutPanel;
  private JTextField keySize;

  public JTextField getKeySize() {
    return keySize;
  }

  public JTextField getCipherSpec() {
    return cipherSpec;
  }

  public EncryptionUpdatePanel() {
    this.add(layoutPanel);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    layoutPanel = new JPanel();
    layoutPanel.setLayout(new GridBagLayout());
    final JLabel label1 = new JLabel();
    label1.setHorizontalAlignment(0);
    label1.setMaximumSize(new Dimension(2147483647, 350));
    label1.setPreferredSize(new Dimension(500, 300));
    label1.setText("<html>You can enter a cipher specification below. If Java supports it the program will try to use it. If you get errors, STOP and set it to the default value of AES/GCM/NoPadding <br> <br>The program makes 9 back up copies automatically, but if you edit 9 times that will cause 9 saves. In the case where Java can write with the new cipher but not read the data, all passwords would be lost. Such a thing can happen if the new cipher has additional or different input vector requirements. If the default implementation uses a random value when writing and the value used is not preserved (because the current code knows nothing about it), reading what was written may be impossible. The good news is that the save format includes the details on which cipher to use when reading so even if you changed this default, it will be ingored for reading an old backup<br><br> This feature is for expert use only, and experts should make a separate backup in a different location. If you don't know what a cipher specification is, don't touch this.</html>");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(label1, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer1, gbc);
    final JLabel label2 = new JLabel();
    label2.setText("New Cipher to Try:");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(label2, gbc);
    cipherSpec = new JTextField();
    cipherSpec.setColumns(25);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(cipherSpec, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer2, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer4, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer5, gbc);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer6, gbc);
    final JLabel label3 = new JLabel();
    label3.setText("New Key Size:");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(label3, gbc);
    keySize = new JTextField();
    keySize.setColumns(5);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(keySize, gbc);
    final JLabel label4 = new JLabel();
    label4.setPreferredSize(new Dimension(500, 80));
    label4.setText("<html><body><p >Please note that for the default algorithm only 128, 192 and 256 are valid key sizes. If you change this, you need to respecify your password (same is ok, but if you mistype it it will change)</p></body></html>");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 7;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(label4, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer7, gbc);
    final JPanel spacer8 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 8;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer8, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return layoutPanel;
  }

}
