package com.needhamsoftware.securesrc.ui;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

public class PasswordPanel extends JPanel {
  public JPasswordField getPasswordField() {
    return passwordField;
  }

  private JPasswordField passwordField;
  private JCheckBox showCheckBox;
  private JPanel layoutPanel;

  public PasswordPanel() {
    showCheckBox.addActionListener(new ActionListener() {
      Character orig = null;

      @Override
      public void actionPerformed(ActionEvent e) {
        if (orig == null) {
          orig = passwordField.getEchoChar();
        }
        if (e.getSource() instanceof JCheckBox cb) {
          if (cb.isSelected()) {
            passwordField.setEchoChar((char) 0);
          } else {
            passwordField.setEchoChar(orig);
          }
        }
      }
    });
    this.add(layoutPanel);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    layoutPanel = new JPanel();
    layoutPanel.setLayout(new GridBagLayout());
    passwordField = new JPasswordField();
    passwordField.setColumns(20);
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(passwordField, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer2, gbc);
    showCheckBox = new JCheckBox();
    showCheckBox.setText("Show");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(showCheckBox, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer4, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return layoutPanel;
  }

}
