package com.needhamsoftware.securesrc.ui;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class PasswordPanel extends JPanel {
  public JPasswordField getPasswordField() {
    return passwordField;
  }

  public JPasswordField getConfirmPassword() {
    return confirmPassword;
  }

  private JPasswordField passwordField;
  private JCheckBox showCheckBox;
  private JPanel layoutPanel;
  private JPasswordField confirmPassword;
  private JCheckBox showConfirm;
  private JButton externalOkButton; // button used by the JOptionPane/dialog displaying us.

  public PasswordPanel() {
    showCheckBox.addActionListener(new ActionListener() {
      Character orig = null;

      @Override
      public void actionPerformed(ActionEvent e) {
        if (orig == null) {
          orig = passwordField.getEchoChar();
        }
        if (e.getSource() instanceof JCheckBox cb) {
          if (cb.isSelected()) {
            passwordField.setEchoChar((char) 0);
          } else {
            passwordField.setEchoChar(orig);
          }
        }
      }
    });
    showConfirm.addActionListener(new ActionListener() {
      Character orig = null;

      @Override
      public void actionPerformed(ActionEvent e) {
        if (orig == null) {
          orig = confirmPassword.getEchoChar();
        }
        if (e.getSource() instanceof JCheckBox cb) {
          if (cb.isSelected()) {
            confirmPassword.setEchoChar((char) 0);
          } else {
            confirmPassword.setEchoChar(orig);
          }
        }
      }
    });

    this.add(layoutPanel);
    DocumentListener checkConfirm = new DocumentListener() {

      @Override
      public void insertUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        update();
      }

      private void update() {
        char[] password = passwordField.getPassword();
        char[] confirm = confirmPassword.getPassword();
        if (confirmPassword.isVisible() && !Arrays.equals(password, confirm)) {
          confirmPassword.setBackground(new Color(255, 180, 180));
          passwordField.setBackground(new Color(255, 180, 180));
          externalOkButton.setEnabled(false);
        } else {
          confirmPassword.setBackground(new Color(255, 255, 255));
          passwordField.setBackground(new Color(255, 255, 255));
          externalOkButton.setEnabled(true);
        }
      }

    };
    confirmPassword.getDocument().addDocumentListener(checkConfirm);
    passwordField.getDocument().addDocumentListener(checkConfirm);
  }


  public void setExternalOkButton(JButton externalOkButton) {
    this.externalOkButton = externalOkButton;
  }

  public void requireConfirm(boolean required) {
    if (!required) {
      confirmPassword.setVisible(false);
      showConfirm.setVisible(false);
    }
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    layoutPanel = new JPanel();
    layoutPanel.setLayout(new GridBagLayout());
    passwordField = new JPasswordField();
    passwordField.setColumns(20);
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(passwordField, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer2, gbc);
    showCheckBox = new JCheckBox();
    showCheckBox.setText("Show");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(showCheckBox, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    layoutPanel.add(spacer4, gbc);
    confirmPassword = new JPasswordField();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    layoutPanel.add(confirmPassword, gbc);
    showConfirm = new JCheckBox();
    showConfirm.setText("Show");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    layoutPanel.add(showConfirm, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return layoutPanel;
  }

}
